server:
  port: 8033

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    codecs:
      max-in-memory-size: 50MB

triage:
  base-url: http://127.0.0.1:8000


# local training/demo knobs
bds:
  data-dir: data
  train-csv: data/training.csv
  model-file: data/model.json
  retrain-every: 5
  route-threshold-mb: 3500

memSpike:
  thresholdMb: 3500

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  datadog:
    metrics:
      export:
        enabled: true
        api-key: ${DATADOG_API_KEY:}
        step: 30s
        application-key: ${DATADOG_APP_KEY:}
        host-tag: instance
        uri: https://api.datadoghq.com
