server:
  port: 8033

spring:
  codec:
    max-in-memory-size: 50MB   # for WebFlux body aggregation in this demo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

triage:
  base-url: http://127.0.0.1:8000

memSpike:
  thresholdMb: 3500

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  datadog:
    metrics:
      export:
        enabled: true
        api-key: ${DATADOG_API_KEY:}
        step: 30s
        application-key: ${DATADOG_APP_KEY:}
        host-tag: instance
        uri: https://api.datadoghq.com
